services:
  xbot:
    image: ghcr.io/debugninjaslayer/xbot:v0.0.2-2025-04-16-10-43-08
    ports:
      - "${PORT:-13000}:3000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TWITTER_APP_KEY=${TWITTER_APP_KEY}
      - TWITTER_APP_SECRET=${TWITTER_APP_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_SECRET=${TWITTER_ACCESS_SECRET}
      - CALLBACK_URL=${CALLBACK_URL}
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true