name: Build Docker Images

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/debugninjaslayer/xbot:latest
            ghcr.io/debugninjaslayer/xbot:${{ github.ref_name }}
            ghcr.io/debugninjaslayer/xbot:${{ github.sha }}
      
      - name: Clean old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: xbot
          package-type: container
          min-versions-to-keep: 5
          delete-only-untagged-versions: true